version: "3.8"
services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    build: 
      context: ./cassandra
      dockerfile: Dockerfile
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_NUM_TOKENS: "256"
      CASSANDRA_DC: "DC1"
      CASSANDRA_RACK: "RAC1"
      CASSANDRA_ENDPOINT_SNITCH: "SimpleSnitch"
  fastapi_app1:
    image: fastapi_app1
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - cassandra
    container_name: ${SERVER_HOST_1}
    restart: always
    environment:
      SERVER_HOST: ${SERVER_HOST_1}
      SERVER_PORT: ${SERVER_PORT_1}
      CASSANDRA_HOST: cassandra
    ports:
      - ${SERVER_PORT_1}:8000
    volumes:
      - ./backend:/backend
  fastapi_app2:
    image: fastapi_app2
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - cassandra
    container_name: ${SERVER_HOST_2}
    restart: always
    environment:
      SERVER_HOST: ${SERVER_HOST_2}
      SERVER_PORT: ${SERVER_PORT_2}
      CASSANDRA_HOST: cassandra
    ports:
      - ${SERVER_PORT_2}:8000
    volumes:
      - ./backend:/backend
  fastapi_app3:
    image: fastapi_app3
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - cassandra
    container_name: ${SERVER_HOST_3}
    restart: always
    environment:
      SERVER_HOST: ${SERVER_HOST_3}
      SERVER_PORT: ${SERVER_PORT_3}
      CASSANDRA_HOST: cassandra
    ports:
      - ${SERVER_PORT_3}:8000
    volumes:
      - ./backend:/backend

  nginx:
    image: nginx
    restart: always
    env_file: .env
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - fastapi_app1
      - fastapi_app2
      - fastapi_app3