@startuml
title UseCases
left to right direction
skinparam actorStyle awesome


rectangle "Central"{
    usecase start_stop as "start/stop election"
    usecase results as "Show election results"
    usecase register_node as "(un-)register node"
}

actor Voter
actor central_admin as "Federal Administrator"
actor node_admin as "Node Administrator"

rectangle "Node"{
    usecase vote
    usecase manage_constituency_candidates as "manage candidates"
    usecase authenticate_voter as "authenticate voter"

}

Voter --> authenticate_voter
results <-- :Voter: 
:Voter: --> vote

:node_admin: --> manage_constituency_candidates
register_node <-- node_admin

start_stop <-- central_admin


:Central: --> :Node: :party list
:Central: --> :Node: :redirect voter
:Node: --> :Central: : constituency election results







@enduml